site_name: ovs学习 - cyent笔记
site_description: Open vSwitch学习笔记
site_author: cyent
site_url: https://cyent.github.io/ovs/

repo_name: 'cyent/ovs'
repo_url: 'https://github.com/cyent/ovs'

theme: material

extra:
  palette:
    primary: 'Blue Grey'
    accent: 'Pink'
  feature:
    tabs: false
  social:
    - type: github
      link: https://github.com/cyent
  #font:
    #text: 'Ubuntu'
    #code: 'Ubuntu Mono'

markdown_extensions:
    - admonition
    - codehilite(guess_lang=false,linenums=false)
    - toc(permalink=true)
    - footnotes
    - meta
    - def_list
    - pymdownx.arithmatex
    - pymdownx.betterem(smart_enable=all)
    - pymdownx.caret
    - pymdownx.critic
    - pymdownx.details
    - pymdownx.emoji:
        emoji_generator: !!python/name:pymdownx.emoji.to_png
        #emoji_generator: !!python/name:pymdownx.emoji.to_svg
        #emoji_generator: !!python/name:pymdownx.emoji.to_png_sprite
        #emoji_generator: !!python/name:pymdownx.emoji.to_svg_sprite
        #emoji_generator: !!python/name:pymdownx.emoji.to_awesome
        #emoji_generator: !!python/name:pymdownx.emoji.to_alt
    - pymdownx.inlinehilite
    - pymdownx.magiclink
    - pymdownx.mark
    - pymdownx.smartsymbols
    - pymdownx.superfences
    - pymdownx.tasklist
    - pymdownx.tilde

extra_javascript:
    - 'js/extra.js'
    - 'js/baidu-tongji.js'
    - 'https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-MML-AM_CHTML'

pages:
    - 一. 介绍: index.md
    - 二. 安装: install.md
    - 三. ovs: ovs.md
    - 四. openflow: openflow.md
    - 五. 实验:
        - 1. 实验1: test/test1.md
        - 2. 性能测试: test/stress.md
    - 六. 附录:
        - 1. 参考资料: appendix/doc.md
        - 2. ovs数据流量及限速: appendix/traffic.md
        - 3. NXM: appendix/nxm.md
        - 4. Neutron流表分析: appendix/neutron.md
        - 5. MAC地址掩码: appendix/mac_mask.md
    - 七. 联系方式: contact.md
